//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mnemonics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keyword
    {
        public long KeywordsId { get; set; }
        public string ChapterNo { get; set; }
        public string ConceptToRemember { get; set; }
        public string Mnemonics { get; set; }
        public string KeyID { get; set; }
        public string AddedBy { get; set; }
        public string Visibile { get; set; }
        public string Deleted { get; set; }
        public long CategoryId { get; set; }
        public string Logo { get; set; }
    }
}
