//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mnemonics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recover
    {
        public long UserId { get; set; }
        public string StudentID { get; set; }
        public string RecoverHash { get; set; }
        public string PreviousEmail { get; set; }
        public string PreviousPassword { get; set; }
        public string PreviousRecoverHash { get; set; }
    }
}
